name: YogiSTRONG
description: Kundalini Yoga with Gurumantra Kaur

#baseurl: http://zblservices.github.io/yogistrong.github.io
baseurl:
excerpt_separator: <!--more-->

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
